### ISSUE TITLE
Additions I would add to the README and Notes.md files

### ISSUE THREAD

**Issue by TheTechChild** [sethhaskellcondie/the-game-pensive-api#22]
This is a solid project, and it's well-documented. You have done an excellent job making it understandable to another engineer who is just picking up the project for the first time. You've explained your reasoning for the project's design very well, which will be appreciated by those trying to read and understand your project.

There are a couple of things I would add/change:
- In `README.md`:
  - Add the following line to the setup instructions: "-Download Maven, if on macOS: `brew install maven && echo -e "\nChecking maven version\n" && mvn -version`". I was unfamiliar with maven, but I found that it could be installed via homebrew on macos; I can easily see a hiring manager not taking the time to figure out how to install maven if they haven't dealt with it before.
- In `Notes.md`:
  - There is one passage that isn't clear in your `## Return Body` section where a spelling error requires that the reader think for a moment to parse out what you were meaning. The sentence in particular is: "for example a DELETE reuqest will usually not return a body in this date will be blank". I have included the section below with edits that would make it clear to the reader.
  
```
## Return Body
The body of requests was inspired by the JSON API format. Responses will have "data" and "errors" attributes as part of the body. If the request was successful, then the errors will return with a null value. Otherwise, the data will be null, and the errors will display one or more messages. This will illustrate when the response was intentional or not. For example, a DELETE request will usually not return a body as the data will be blank, and the errors will be null, showing that the request was successful; there was just no data to return.
```

**Comment by sethhaskellcondie** [comment]
Fixed with this PR: https://github.com/sethhaskellcondie/the-game-pensive-api/pull/23
